spring:
  # security:
  #   user:
  #     name: user
  #     password: testpw
  datasource:
    username: coup
    url: jdbc:mysql:3.36.196.244
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update

  
  devtools:
    restart:
      # 로깅시 재시작 방지
      exclude: logs/**
  
  output:
    ansi:
      enabled: always

server:
  port: 5000
  # servlet:
  #   context-path: /index


