spring:
  security:
    user:
      name: user
      password: testpw

  devtools:
    restart:
      # 로깅시 재시작 방지
      exclude: logs/**
  
  output:
    ansi:
      enabled: always

server:
  port: 5000
  datasource:
      username: admin
      url: jdbc:mysql://3.36.196.244:3306/coup
      driverClassName: com.mysql.jdbc.Driver
      password: 12345
  jpa:
      hibernate:
          ddl-auto: update
